# Generated by Django 3.0.3 on 2020-03-15 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('depid', models.IntegerField(max_length=1000, primary_key=True, serialize=False)),
                ('depname', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('fname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=1000)),
                ('empid', models.IntegerField(max_length=10000, primary_key=True, serialize=False)),
                ('jobtitle', models.CharField(max_length=100)),
                ('evaluatedby', models.CharField(max_length=1000)),
                ('depname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_register.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('managid', models.IntegerField(max_length=1000, primary_key=True, serialize=False)),
                ('managerName', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goalid', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('goaltitle', models.CharField(max_length=1000)),
                ('goaldesc', models.CharField(max_length=10000)),
                ('empcmt', models.CharField(max_length=10000)),
                ('managcmt', models.CharField(max_length=10000)),
                ('stars', models.IntegerField(max_length=10)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_register.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='reportingmanagername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_register.Manager'),
        ),
    ]
