# Generated by Django 3.0.3 on 2020-03-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hiredate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='lastappraisaldate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='duedate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='depid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='stars',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manager',
            name='managid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
