# Generated by Django 3.0.3 on 2020-03-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_auto_20200315_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hiredate',
            field=models.DateField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastappraisaldate',
            field=models.DateField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='goal',
            name='duedate',
            field=models.DateField(verbose_name=''),
        ),
    ]
