# Generated by Django 3.0.3 on 2020-03-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0004_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='empid',
            field=models.IntegerField(),
        ),
    ]
