# Generated by Django 3.0.3 on 2020-03-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0005_auto_20200316_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='password',
        ),
    ]
